---
swagger: "2.0"
info:
  description: "This is the documentation file for ASW Issue Tracker."
  version: "1.0.0"
  title: "Issue Tracker"
host: "----HEROKU-URL-----"
paths:
  /issues:
    get:
      tags:
      - "Issues"
      summary: "Gets all the Issues"
      produces:
      - "application/json"
      parameters:
        - in: query
          name: type
          description: Gets `Issue` objects by type
          required: false
          type: string
          enum:
            - Bug
            - Enhancement
            - Proposal
            - Task
        - in: query
          name: priority
          description: Gets `Issue` objects by priority
          required: false
          type: string
          enum:
            - Trivial
            - Minor
            - Major
            - Critical
            - Blocker
        - in: query
          name: status
          description: Gets `Issue` objects by status
          required: false
          type: string
          enum:
            - New
            - Open
            - On hold
            - Resolved
            - Duplicate
            - Invalid
            - Won't fix
            - Closed
            - New&Open
        - in: query
          name: assignee
          description: Gets `Issue` objects by assignee
          required: false
          type: integer
        - in: query
          name: watcher
          description: Gets `Issue` objects watched by a user
          required: false
          type: integer
      responses:
        '422':
          description: User does not exist
          schema:
            type: object
            properties:
              error:
                example: User with id=1000 does not exist
    post:
      summary: create issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/new":
    get:
      summary: new issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/edit":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: edit issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    patch:
      summary: update issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    put:
      summary: update issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    delete:
      summary: delete issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list issues
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/attachment":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_attachment issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    post:
      summary: create_attachment issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/vote":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    post:
      summary: vote issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/watch":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    post:
      summary: watch issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/status":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    put:
      summary: update_status issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
