---
openapi: 3.0.1
info:
  title: "Issue Tracker"
  version: 1.0.0
servers: 
  - url: https://blooming-dusk-00596.herokuapp.com/
  - url: https://4e3e98d67aee4ae48c9cbc98fb74399f.vfs.cloud9.us-east-2.amazonaws.com/

components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: query       # can be "header", "query" or "cookie"
      name: api_key  # name of the header, query parameter or cookie
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes

paths:

  "/api/issues":
  
    get:
      description: Gets the `Issue` object by the desired category 
      tags:
      - "Issues"
      summary: "Gets all the Issues"
      produces:
        - application/json      
      parameters:
      - in: query
        name: type
        description: Gets `Issue` objects by type
        required: false
        schema:
          type: "string"
          enum:
            - Bug
            - Enhancement
            - Proposal
            - Task
        
      - in: query
        name: priority
        description: Gets `Issue` objects by priority
        required: false
        schema:
          type: "string"
          enum:
            - Trivial
            - Minor
            - Major
            - Critical
            - Blocker
      - in: query
        name: status
        description: Gets `Issue` objects by status
        required: false
        schema:
          type: "string"
          enum:
            - New
            - Open
            - On hold
            - Resolved
            - Duplicate
            - Invalid
            - Won't fix
            - Closed
            - New&Open
      - in: query
        name: assignee
        description: Gets `Issue` objects by assignee
        required: false
        schema:
          type: integer
      - in: query
        name: watcher
        description: Gets `Issue` objects watched by a user
        required: false
        schema:
          type: "string"
      responses:
        '200':
          description: Successful response
          
    post:
      tags:
      - Issues
      summary: "Create a new Issue"
      description: ""
      parameters:
      - in: query
        schema:
          type: "string"
        name: "Title"
        required: true
      - in: query
        schema:
          type: "string"
        name: "Description"
        required: false
      - in: "query"
        name: Type
        description: Set the type of `Issue`
        required: false
        schema:
          type: "string"
          enum:
            - Bug
            - Enhancement
            - Proposal
            - Task
      - in: "query"
        name: Priority
        description: Set the priority of `Issue`
        required: false
        schema:
          type: "string"
          enum:
            - Trivial
            - Minor
            - Major
            - Critical
            - Blocker
      - in: "query"
        name: Status
        description: Set the status of `Issue`
        required: false
        schema:
          type: "string"
          enum:
            - New
            - Open
            - On hold
            - Resolved
            - Duplicate
            - Invalid
            - Won't fix
            - Closed
      - in: "query"
        name: asignee_id
        description: Assigns the `Issue` to the desired user
        required: false
        schema:
          type: integer
      consumes:
      - "application/x-www-form-urlencoded"
      - "application/json"
      produces:
      - "application/json"  
      responses:
        '200':
          description: successful
        405:
          description: "Invalid input"
  "/issues/new":
    get:
      summary: new issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/edit":
    parameters:
    - name: id
      in: path
      schema:
          type: "string"
      description: id
      required: true
    get:
      summary: edit issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}":
    parameters:
    - name: id
      in: path
      schema:
          type: "string"
      description: id
      required: true
    get:
      summary: show issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    put:
      summary: update issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    delete:
      summary: delete issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list issues
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/vote":
    parameters:
    - name: id
      in: path
      schema:
        type: "string"
      description: id
      required: true
    post:
      summary: vote issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/watch":
    parameters:
    - name: id
      in: path
      schema:
        type: "string"
      description: id
      required: true
    post:
      summary: watch issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/status":
    parameters:
    - name: id
      in: path
      schema:
        type: "string"
      description: id
      required: true
    put:
      summary: update_status issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/users":
    get:
      description: Gets the list of `Users` of the Issue Tracker
      tags:
      - Users
      summary: list users
      produce:
        - "application/json" 
      responses:
        '200':
          description: successful
    post:
      description: Creates a new `User` for the Issue Tracker
      tags:
      - Users
      summary: create user
      parameters:
      - name: name
        description: name of the new `User`
        in: query
        schema:
          type: string
        required: true
      - name: email
        description: email of the new `User` of the Issue Tracker
        schema:
          type: string
        in: query
        required: true
      - name: password
        description: password for the login
        schema:
          type: string
        in: query
        required: true
      responses:
        '200':
          description: successful
  "/users/new":
    get:
      tags:
      - Users
      summary: new user
      responses:
        '200':
          description: successful
  "/users/{user_id}/edit":
    parameters:
    - name: user_id
      in: path
      schema:
        type: "string"
      description: user_id to identify the `User`
      required: true
    get:
      description: Get the `User` identified by user_id 
      tags:
      - Users
      summary: edit user
      responses:
        '200':
          description: successful
  "/users/{user_id}":
    parameters:
    - name: user_id
      in: path
      schema:
        type: "string"
      description: user_id to identify the `User`
      required: true
    get:
      description: Get the `User` identified by user_id
      tags:
      - Users
      summary: show user
      responses:
        '200':
          description: successful
    put:
      parameters:
      - name: name
        description: name of the new `User`
        in: query
        schema:
          type: string
        required: false
      - name: email
        description: email of the new `User` of the Issue Tracker
        schema:
          type: string
        in: query
        required: false
      - name: password
        description: password for the login
        schema:
          type: string
        in: query
        required: false
      description: Update the `User` identified by user_id
      tags:
      - Users
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      description: Delete the `User` identified by user_id
      tags:
      - Users
      summary: delete user
      responses:
        '200':
          description: successful


  "/issues/{issue_id}/comments":
    parameters:
    - name: issue_id
      in: path
      schema:
        type: "string"
      description: Gets the `comments` of the `Issue` identified by issue_id
      required: true
    get:
      description: Gets the comments of an Issue identified by issue_id
      tags:
      - Comments
      produces:
      - "application/json"
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      parameters:
      - name: comment_text
        in: path
        schema:
          type: "string"
        description: Write the body of the new `comment` of the `Issue` identified by issue_id
        required: true
      tags:
      - Comments
      summary: create comment
      produces:
      - "application/json"
      responses:
        '200':
          description: successful
  "/issues/{issue_id}/comments/new":
    parameters:
    - name: issue_id
      in: path
      schema:
        type: "string"
      description: issue_id to identify the `Issue` where you want to write a new `comment`
      required: true
    - name: api_key
      in: path
      schema:
        type: "string"
      description: api_key
      required: true
    - name: comment_text
      in: path
      schema:
        type: "string"
      description: Write the body of the new `comment` of the `Issue` identified by issue_id
      required: true
    get:
      tags:
      - Comments
      summary: new comment
      responses:
        '200':
          description: successful
  "/issues/{issue_id}/comments/{comment_id}/edit":
    parameters:
    - name: issue_id
      in: path
      schema:
        type: "string"
      description: issue_id to identify the `Issue` where you want to edit the `comment`
      required: true
    - name: comment_id
      in: path
      schema:
        type: "string"
      description: comment_id to identify the `Comment` you want to edit
      required: true
    - name: comment_text
      in: path
      schema:
        type: "string"
      description: Write the body of the `comment` of the `Issue` identified by issue_id you want to edit
      required: true
    get:
      tags:
      - Comments
      summary: edit comment
      responses:
        '200':
          description: successful
  "/issues/{issue_id}/comments/{comment_id}":
    parameters:
    - name: issue_id
      in: path
      schema:
        type: "string"
      description: issue_id to identify the `Issue` where is the `comment`
      required: true
    - name: comment_id
      in: path
      schema:
        type: "string"
      description: comment_id to identify the `Comment`
      required: true
    get:
      description: Gets the `comment` identified by comment_id of the `Issue` identified by issue_id
      tags:
      - Comments
      summary: show comment
      responses:
        '200':
          description: successful
    put:
      description: Puts the `comment` identified by comment_id of the `Issue` identified by issue_id
      tags:
      - Comments
      parameters:
      - name: comment_text
        in: path
        schema:
          type: "string"
        description: Write the body of the `comment` identified by comment_id of the `Issue` identified by issue_id
        required: true
      summary: update comment
      responses:
        '200':
          description: successful
    delete:
      tags:
      - Comments
      summary: delete comment
      responses:
        '200':
          description: successful
  