---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: blog
        in: body
        schema:
          type: object
          properties:
            title:
              type: string
            content:
              type: string
          required:
          - title
          - content
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
  "/blogs/{id}":
    get:
      summary: Retrieves a blog
      tags:
      - Blogs
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: blog found
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              content:
                type: string
            required:
            - id
            - title
            - content
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
  "/issues":
    get:
      summary: list issues
      tags:
      - Issues
      responses:
        '200':
          description: successful
    post:
      summary: create issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/new":
    get:
      summary: new issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/edit":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: edit issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    patch:
      summary: update issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    put:
      summary: update issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    delete:
      summary: delete issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list issues
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/attachment":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show_attachment issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
    post:
      summary: create_attachment issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/vote":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    post:
      summary: vote issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/watch":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    post:
      summary: watch issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
  "/issues/{id}/status":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    put:
      summary: update_status issue
      tags:
      - Issues
      responses:
        '200':
          description: successful
